name: Deploy CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Use Node.js 16.15.1
      uses: actions/setup-node@v2
      with:
        node-version: 16.15.1
        cache: 'pnpm'

    - name: Caching
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: pnpm install
    
    - name: MegaLinter
      id: ml
      uses: megalinter/megalinter/flavors/javascript@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLY_FIXES: none
        SHOW_ELAPSED_TIME: true
        FILEIO_REPORTER: true
        LINTER_RULES_PATH: /
        FILTER_REGEX_INCLUDE: (src/)
        FILTER_REGEX_EXCLUDE: (src/assets/sdks/)
        PRINT_ALPACA: false
        PRINT_ALL_FILES: false

    - name: Build
      run: |
        pnpm run build

    # - name: Copy Files
    #   uses: cross-the-world/ssh-scp-ssh-pipelines@latest
    #   with:
    #     host: ${{ secrets.HOST }}
    #     user: ${{ secrets.USER }}
    #     pass: ${{ secrets.PASS }}
    #     scp: |
    #       ./dist/* => /home/github/app/
    #     last_ssh: |
    #       ls -la
